//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int Id { get; set; }
        public Nullable<int> MakeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year { get; set; }
        public string Edition { get; set; }
        public string Engine { get; set; }
        public string BodyType { get; set; }
        public string Transmission { get; set; }
    }
}
